- .github/workflows/docker/test_entrypoint.sh
- cfd/confidential_transaction.py
- integration_test/test_entrypoint.sh
- integration_test/tests/test_elements.py
- test: add elementsd test
```bash
```
** Reviewer **
> test: add elementsd test

- cfd/confidential_transaction.py
- tests/test_confidential_transaction.py
- fix: parse confidential value from unblind tx
- fix: add get address by elements
- feat: add support API
- test: add decoded value check API
```bash
```
** Reviewer **
> fix: ct value bug, etc.

- .github/workflows/check_pre-merge_develop.yml
- .github/workflows/check_pre-merge_master.yml
- .github/workflows/check_pre-merge_sprint.yml
- cfd/address.py
- cfd/confidential_address.py
- cfd/confidential_transaction.py
- cfd/descriptor.py
- cfd/hdwallet.py
- cfd/key.py
- cfd/script.py
- cfd/transaction.py
- cfd/util.py
- integration_test/tests/test_bitcoin.py
- integration_test/tests/test_elements.py
- tests/data/elements_address_test.json
- tests/data/elements_transaction_test.json
- tests/data/key_test.json
- tests/test_address.py
- tests/test_confidential_transaction.py
- tests/test_transaction.py
- tests/util.py
- feat: typing support
```bash
```
** Reviewer **
> feat: typing support

- cfd/confidential_transaction.py
- tests/test_confidential_transaction.py
- feat: split get_address
- split to get_address and get_confidential_address
```bash
```
** Reviewer **
> feat: split get_address

- .github/workflows/check_pre-merge_develop.yml
- .github/workflows/check_pre-merge_master.yml
- .github/workflows/check_pre-merge_sprint.yml
- .github/workflows/code_scanner.yml
- .github/workflows/docker/test_bitcoin_entrypoint.sh
- test: add bitcoin 0.21.0
```bash
```
** Reviewer **
> test: add bitcoin 0.21.0

- .vscode/settings.json
- cfd-python.code-workspace
- cfd/__init__.py
- cfd/address.py
- cfd/confidential_address.py
- cfd/confidential_transaction.py
- cfd/crypto.py
- cfd/descriptor.py
- cfd/hdwallet.py
- cfd/key.py
- cfd/psbt.py
- cfd/script.py
- cfd/transaction.py
- cfd/util.py
- local_resource/external_project_local_setting.config
- setup.cfg
- tests/data/common_test.json
- tests/data/psbt_test.json
- tests/test_common.py
- tests/test_confidential_transaction.py
- tests/test_psbt.py
- tests/test_transaction.py
- tests/util.py
- feat: add psbt
- feat: add workspace setting.
- style: lint
```bash
```
** Reviewer **
> feat: add psbt

- .github/workflows/check_pre-merge_master.yml
- tests/data/psbt_test.json
- tests/test_psbt.py
- test: update test expect.
```bash
```
** Reviewer **
> test: update test expect.

- cfd/confidential_transaction.py
- cfd/descriptor.py
- cfd/hdwallet.py
- cfd/key.py
- cfd/psbt.py
- cfd/script.py
- cfd/transaction.py
- cfd/util.py
- tests/test_psbt.py
- fix: typing.
- with mypy
```bash
```
** Reviewer **
> fix: typing.

- .github/workflows/check_pre-merge_develop.yml
- .github/workflows/check_pre-merge_master.yml
- .github/workflows/check_pre-merge_sprint.yml
- .github/workflows/docker/test_entrypoint.sh
- cfd-python.code-workspace
- integration_test/elements.conf
- integration_test/tests/test_elements.py
- local_resource/external_project_local_setting.config
- tests/data/elements_coin_test.json
- tests/test_confidential_transaction.py
- test: update ci
```bash
```
** Reviewer **
> test: update ci

- cfd/taproot.py
- tests/test_address.py
- fix: add filter target node list on script tree
```bash
```
** Reviewer **
> fix: add filter target node list on script tree

- README.md
- local_resource/external_project_local_setting.config
- doc: update README.md
- upgrade: update cfd version 
```bash
```
** Reviewer **
> doc: update README.md

- cfd/taproot.py
- cfd/util.py
- local_resource/external_project_local_setting.config
- tests/data/address_test.json
- tests/test_address.py
- fix: rename roothash to basehash
- fix: add getting tapbranch API
- test: add json scenario (from cfd-js) 
```bash
```
** Reviewer **
> fix: taproot

- local_resource/external_project_local_setting.config
- tests/data/descriptor_test.json
- tests/data/elements_transaction_test.json
- tests/data/key_test.json
- tests/data/script_test.json
- tests/data/transaction_test.json
- tests/test_confidential_transaction.py
- tests/test_key.py
- tests/test_script.py
- tests/test_transaction.py
- test: sighash rangeproof
```bash
```
** Reviewer **
> test: sighash rangeproof

- cfd/hdwallet.py
- cfd/util.py
- tests/data/bip32/README.md
- tests/data/bip39/README.md
- tests/data/elements_transaction_test.json
- tests/data/hdwallet_test.json
- tests/test_hdwallet.py
- feat: support bip49/bip84
- feat: add custom prefix API 
```bash
```
** Reviewer **
> feat: add custom prefix API

- docker-compose.yml
- integration_test/test_entrypoint.sh
- integration_test/tests/test_elements.py
- test: add dynafed test
```bash
```
** Reviewer **
> test: add dynafed

- .github/workflows/code_scanner.yml
- test: update code scan
```bash
```
** Reviewer **
> test: update code scan

- .github/workflows/create_release-and-upload.yml
- feat: update release-asset python version
```bash
```
** Reviewer **
> feat: update release-asset python version

- .github/workflows/create_release-and-upload.yml
- fix: asset name on macos
```bash
```
** Reviewer **
> fix: asset name on macos

- .github/workflows/check_pre-merge_develop.yml
- .github/workflows/check_pre-merge_master.yml
- .github/workflows/check_pre-merge_sprint.yml
- Pipfile
- cfd/confidential_transaction.py
- cfd/transaction.py
- cfd/util.py
- docker-compose.yml
- docker/ubuntu2204.dockerfile
- local_resource/external_project_local_setting.config
- tools/build_and_test_for_docker.sh
#92 
- fix: wrapper CAPI for estimateFee
- test: add ubuntu22.04
```bash
```
** Reviewer **
> fix: wrapper CAPI for estimateFee

- .github/workflows/check_pre-merge_develop.yml
- .github/workflows/check_pre-merge_master.yml
- .github/workflows/check_pre-merge_sprint.yml
- test: add python3.11
```bash
```
** Reviewer **
> test: add python3.11

- .github/workflows/check_pre-merge_develop.yml
- .github/workflows/check_pre-merge_master.yml
- .github/workflows/check_pre-merge_sprint.yml
- .github/workflows/code_scanner.yml
- .github/workflows/create_release-and-upload.yml
- .github/workflows/docker/test_entrypoint.sh
- docker-compose.yml
- integration_test/test_bitcoin_entrypoint.sh
- integration_test/test_entrypoint.sh
- integration_test/tests/helper.py
- integration_test/tests/test_elements.py
- feat: update elements on CI
- test: update actions
```bash
```
** Reviewer **
> feat: update elements on CI, update actions
